const colors = [
  'red',
  'blue',
  'green',
  'pink',
  'orange',
  'yellow',
  'black',
  'white',
  'purple',
  'brown',
  'cyan',
  'lime',
];

const map = {
  cafeteria: {
    aliases: ['cafeteria'],
    exits: { w: 'medbay', e: 'weapons', s: 'admin' },
    vents: ['admin', 'oxygen'],
  },
  medbay: {
    aliases: ['medbay', 'medical'],
    exits: { w: 'upper', e: 'cafeteria' },
    vents: ['security', 'electrical'],
  },
  admin: {
    aliases: ['admin', 'administration'],
    exits: { n: 'cafeteria', s: 'storage' },
    vents: ['cafeteria', 'oxygen'],
  },
  weapons: {
    aliases: ['weapons'],
    exits: { w: 'cafeteria', s: 'oxygen' },
    vents: ['navigation', 'shields'],
  },
  upper: {
    aliases: ['upper reactor', 'upper'],
    exits: { e: 'medbay', s: 'reactor' },
    vents: ['reactor'],
  },
  lower: {
    aliases: ['lower reactor', 'lower'],
    exits: { n: 'reactor', e: 'electrical' },
    vents: ['reactor'],
  },
  reactor: {
    aliases: ['reactor'],
    exits: { n: 'upper', e: 'security', s: 'lower' },
    vents: ['upper', 'lower'],
  },
  security: {
    aliases: ['security', 'cams', 'cameras'],
    exits: { w: 'reactor' },
    vents: ['medbay', 'electrical'],
  },
  oxygen: {
    aliases: ['oxygen', 'o2', 'oxy'],
    exits: { n: 'weapons', e: 'navigation', s: 'shields' },
    vents: ['cafeteria', 'admin'],
  },
  navigation: {
    aliases: ['navigation', 'nav'],
    exits: { w: 'oxygen' },
    vents: ['weapons', 'shields'],
  },
  shields: {
    aliases: ['shields', 'shield'],
    exits: { n: 'oxygen', w: 'communications' },
    vents: ['weapons', 'navigation'],
  },
  communications: {
    aliases: ['communications', 'com', 'comm', 'coms', 'comms'],
    exits: { w: 'storage', e: 'shields' },
  },
  storage: {
    aliases: ['storage'],
    exits: { n: 'admin', w: 'electrical', e: 'communications' },
  },
  electrical: {
    aliases: ['electrical'],
    exits: { w: 'lower', e: 'storage' },
    vents: ['security', 'medbay'],
  },
};

const tasks = [
  {
    select: true,
    id: 'align_engine',
    description: 'Align Engine Output',
    place: 'upper',
    type: 'long',
    parallelTasks: 'align_engine',
    successMsg: 'You successfully align the output of the Upper Reactor!',
  },
  {
    select: false,
    id: 'align_engine',
    description: 'Align Engine Output',
    place: 'lower',
    type: 'long',
    parallelTasks: 'align_engine',
    successMsg: 'You successfully align the output of the Lower Reactor!',
  },
  {
    select: true,
    id: 'calibrate_distributor',
    description: 'Calibrate Distributor',
    place: 'electrical',
    type: 'short',
    successMsg: 'You successfully calibrate the distributor!',
  },
  {
    select: true,
    id: 'chart_course',
    description: 'Chart Course',
    place: 'navigation',
    type: 'short',
    successMsg: 'You successfully chart the course!',
  },
  {
    select: true,
    id: 'clean_filter',
    description: 'Clean Filter',
    place: 'oxygen',
    type: 'short',
    successMsg: 'You successfully clean the filter!',
  },
  {
    select: true,
    id: 'clear_asteroids:1',
    description: 'Clear Asteroids (x3)',
    place: 'weapons',
    type: 'long',
    next: 'clear_asteroids:2',
    successMsg:
      'You shoot down several asteroids!\n\nYou will need to repeat this task 2 more times.',
  },
  {
    select: false,
    id: 'clear_asteroids:2',
    description: 'Clear Asteroids (x2)',
    place: 'weapons',
    type: 'long',
    next: 'clear_asteroids:3',
    successMsg:
      'You shoot down several asteroids!\n\nYou will need to repeat this task 1 more time.',
  },
  {
    select: false,
    id: 'clear_asteroids:3',
    description: 'Clear Asteroids',
    place: 'weapons',
    type: 'long',
    successMsg: 'You successfully clear all the asteroids!',
  },
  {
    select: true,
    id: 'divert_power',
    description: 'Divert Power',
    place: 'electrical',
    type: 'short',
    next: 'accept_power',
    successMsg:
      'You divert the power.\n\nYou must now accept the power elsewhere. (check your task list)',
  },
  {
    select: false,
    id: 'accept_power',
    description: 'Accept Power',
    place: [
      'communications',
      'lower',
      'navigation',
      'oxygen',
      'security',
      'shields',
      'upper',
      'weapons',
    ],
    type: 'short',
    successMsg: 'You successfully accept the diverted power!',
  },
  {
    select: true,
    id: 'empty_chute:1',
    description: 'Empty Chute',
    place: 'cafeteria',
    type: 'long',
    next: 'empty_chute:2',
    successMsg:
      'You empty the trash chute.\n\nYou must now empty the chute in Storage.',
  },
  {
    select: false,
    id: 'empty_chute:2',
    description: 'Empty Chute',
    place: 'storage',
    type: 'long',
    successMsg: 'You successfully empty the trash chute!',
  },
  {
    select: true,
    id: 'fix_wiring:1',
    description: 'Fix Wiring',
    place: ['electrical', 'storage'],
    type: 'common',
    next: 'fix_wiring:2',
    successMsg:
      'You fix the wires.\n\nCheck your task list for another wire fixing task.',
  },
  {
    select: false,
    id: 'fix_wiring:2',
    description: 'Fix Wiring',
    place: ['admin', 'navigation'],
    type: 'common',
    next: 'fix_wiring:3',
    successMsg:
      'You fix the wires.\n\nCheck your task list for the final wire fixing task.',
  },
  {
    select: false,
    id: 'fix_wiring:3',
    description: 'Fix Wiring',
    place: ['cafeteria', 'security'],
    type: 'common',
    successMsg: 'You successfully fix the wires!',
  },
  {
    select: true,
    id: 'fuel_engines:1',
    description: 'Fill Gas Tank',
    place: 'storage',
    type: 'long',
    next: 'fuel_engines:2',
    successMsg:
      'You fill the gas tank.\n\nYou must now fuel the Upper Reactor.',
  },
  {
    select: false,
    id: 'fuel_engines:2',
    description: 'Fuel Reactor',
    place: 'upper',
    type: 'long',
    next: 'fuel_engines:3',
    successMsg:
      'You fuel the Upper Reactor.\n\nYou must now refill your gas tank.',
  },
  {
    select: false,
    id: 'fuel_engines:3',
    description: 'Fill Gas Tank',
    place: 'storage',
    type: 'long',
    next: 'fuel_engines:4',
    successMsg:
      'You refill your gas tank.\n\nYou must now fuel the Lower Reactor!',
  },
  {
    select: false,
    id: 'fuel_engines:4',
    description: 'Fuel Reactor',
    place: 'lower',
    type: 'long',
    successMsg: 'You successfully fuel the reactor!',
  },
  {
    select: true,
    id: 'prepare_samples',
    description: 'Prepare Samples',
    place: 'medbay',
    type: 'long',
    next: 'inspect_samples',
    successMsg:
      'You start to prepare the samples.\n\nCome back in 5 turns to inspect the samples.',
  },
  {
    select: false,
    id: 'inspect_samples',
    description: 'Inspect Samples',
    place: 'medbay',
    type: 'long',
    successMsg: 'You successfully inspect the samples!',
  },
  {
    select: true,
    id: 'prime_shields',
    description: 'Prime Shields',
    place: 'shields',
    type: 'short',
    successMsg: 'You successfully prime the shields!',
  },
  {
    select: true,
    id: 'stabilize_steering',
    description: 'Stabilize Steering',
    place: 'navigation',
    type: 'short',
    successMsg: 'You successfully stabilize the steering!',
  },
  {
    select: true,
    id: 'start_reactor',
    description: 'Start Reactor',
    place: 'reactor',
    type: 'short', // supposed to be long
    successMsg: 'You successfully start the reactor!',
  },
  {
    select: true,
    id: 'submit_scan',
    description: 'Submit Scan',
    place: 'medbay',
    type: 'short',
    successMsg: 'You successfully submit your medbay scan!',
  },
  {
    select: true,
    id: 'swipe_card',
    description: 'Swipe Card',
    place: 'admin',
    type: 'common',
    successMsg: 'You successfully swipe your card!',
  },
  {
    select: true,
    id: 'unlock_manifolds',
    description: 'Unlock Manifolds',
    place: 'reactor',
    type: 'short',
    successMsg: 'You successfully unlock the manifolds!',
  },
  {
    select: true,
    id: 'download',
    description: 'Download Data',
    place: [
      'cafeteria',
      'communications',
      'electrical',
      'navigation',
      'weapons',
    ],
    type: 'short',
    next: 'upload',
    successMsg:
      'You download the data.\n\nYou must now upload the data in Admin.',
  },
  {
    select: true,
    id: 'upload',
    description: 'Upload Data',
    place: 'admin',
    type: 'short',
    successMsg: 'You successfully upload the data!',
  },
];

module.exports = {
  colors,
  map,
  tasks,
};
